/**
 * Annual report generator.
 *
 * Aggregates 12 months of financial data into a comprehensive yearly summary.
 * Includes month-over-month trends, annual category/merchant rankings,
 * savings rate calculation, and investment activity totals.
 */

import * as fs from 'fs';
import * as path from 'path';
import { Transaction } from '../types';
import { REPORTS_DIR, getUserContext } from '../config';
import { buildMonthData, filterByDate, getCategoryTotals, getMerchantTotals } from '../data';
import { classifyTransaction } from '../classifier';
import { callModel, lastModelUsed } from '../ai-model';
import { sendEmail } from '../email';
import { renderConnectorStatusBlock } from '../connector-status';
import { extractFragment } from './shared';

export async function generateAnnualReport(transactions: Transaction[], months: string[]): Promise<void> {
  console.log(`Generating annual report: ${months[0]} — ${months[months.length - 1]}...`);

  const monthlyData = await Promise.all(months.map(m => buildMonthData(transactions, m)));
  const totalIncome = monthlyData.reduce((s, d) => s + d.income.total, 0);
  const totalLiving = monthlyData.reduce((s, d) => s + d.expenses.living, 0);
  const totalFreelance = monthlyData.reduce((s, d) => s + d.expenses.freelance, 0);

  // Aggregate categories and merchants across all months
  const allExpenses = months.flatMap(m => {
    const txns = filterByDate(transactions, `${m}-01`, `${m}-31`);
    return txns.filter(t => {
      const c = classifyTransaction(t);
      return (c === 'living' && t.amount < 0) || c === 'atm' || c === 'donation';
    });
  });
  const annualCategories = getCategoryTotals(allExpenses);
  const annualMerchants = getMerchantTotals(allExpenses, 20);

  const monthlyTable = monthlyData.map(d =>
    `| ${d.month} | ₪${d.income.salary.toLocaleString()} | ₪${d.income.freelance.toLocaleString()} | ₪${Math.abs(d.expenses.living).toLocaleString()} | ₪${d.surplus.toLocaleString()} |`
  ).join('\n');

  const prompt = `${getUserContext()}

## Annual Data: ${months[0]} — ${months[months.length - 1]}

### Monthly Overview
| חודש | משכורת | פרילנס | הוצאות מחייה | עודף/גירעון |
|------|--------|--------|-------------|-------------|
${monthlyTable}

### Annual Totals
- Total salary: ₪${monthlyData.reduce((s, d) => s + d.income.salary, 0).toLocaleString()}
- Total freelance: ₪${monthlyData.reduce((s, d) => s + d.income.freelance, 0).toLocaleString()}
- Total income: ₪${totalIncome.toLocaleString()}
- Total living expenses: ₪${Math.abs(totalLiving).toLocaleString()}
- Total freelance expenses: ₪${Math.abs(totalFreelance).toLocaleString()}
- Annual surplus: ₪${(totalIncome + totalLiving + totalFreelance).toLocaleString()}
- Savings rate: ${Math.round((totalIncome + totalLiving + totalFreelance) / totalIncome * 100)}%

### Annual Category Breakdown
${annualCategories.map(c => `- ${c.category}: ₪${Math.abs(c.total).toLocaleString()} (${c.count} txns, ₪${Math.round(Math.abs(c.total) / 12).toLocaleString()}/mo avg)`).join('\n')}

### Top 20 Merchants (Annual)
${annualMerchants.map((m, i) => `${i + 1}. ${m.merchant}: ₪${Math.abs(m.total).toLocaleString()} (${m.visits} visits)`).join('\n')}

### Savings (Annual)
- Total savings (הוראות קבע): ₪${Math.abs(monthlyData.reduce((s, d) => s + d.savings, 0)).toLocaleString()}

### Investment Activity (Annual)
- Total purchased: ₪${Math.abs(monthlyData.reduce((s, d) => s + d.investment.purchases, 0)).toLocaleString()}
- Total sold: ₪${monthlyData.reduce((s, d) => s + d.investment.sales, 0).toLocaleString()}
- Total fees: ₪${Math.abs(monthlyData.reduce((s, d) => s + d.investment.fees, 0)).toLocaleString()}

## Task
Generate a comprehensive annual financial report in Hebrew as HTML with inline CSS (email-safe). RTL direction. Modern clean design.
MOBILE-FIRST: this is read mostly on a phone. Do NOT use fixed pixel widths or min-widths.
Make every table width:100% (no horizontal scrolling); keep tables to 3-4 columns max so they
fit a narrow screen — if a table would be wider, drop low-value columns or stack the data.
Use font-size 13px+. The whole report must fit a ~360px-wide viewport.

Structure:
1. תקציר שנתי — key numbers, savings rate
2. הכנסות — monthly income table (salary + freelance)
3. הוצאות מחייה — annual category table with monthly average and % of income
4. מגמות חודשיות — which months were high/low and why
5. Top 20 ספקים — annual merchant ranking
6. חיסכון — annual savings summary
7. פעילות השקעות — annual investment summary
8. הוצאות קבועות vs גמישות — fixed vs flexible breakdown
9. תובנות מרכזיות — 5-7 key insights
10. המלצות — short/medium/long term
11. פוטנציאל חיסכון — specific cuts with estimated savings

Be data-driven. Every number comes from the data above.`;

  const report = await callModel(prompt);
  const modelFooter = `<p style="color:#999;font-size:11px;text-align:center;margin-top:20px;border-top:1px solid #eee;padding-top:8px;">Generated by ${lastModelUsed} on ${new Date().toISOString().split('T')[0]}</p>`;

  // Clean model output to a fragment (avoids nesting a full document that would
  // constrain width), and lead with the connector-status summary.
  let html = renderConnectorStatusBlock() + extractFragment(report);
  html += modelFooter;

  const reportDir = path.join(REPORTS_DIR, 'annual');
  if (!fs.existsSync(reportDir)) fs.mkdirSync(reportDir, { recursive: true });
  const range = `${months[0].substring(0, 4)}-${months[months.length - 1].substring(0, 4)}`;
  fs.writeFileSync(path.join(reportDir, `${range}.md`), report + `\n\n---\n*Generated by ${lastModelUsed} on ${new Date().toISOString().split('T')[0]}*\n`);
  fs.writeFileSync(path.join(reportDir, `${range}.html`), html);
  console.log(`  Saved: annual/${range}.md (model: ${lastModelUsed})`);

  await sendEmail(`סיכום שנתי — ${range}`, html);
}
