/**
 * Deterministic month expense-history renderer.
 *
 * The rest of the daily report is generated by the AI model, which means its
 * markup varies run-to-run. The month expense breakdown is the part the user
 * reads most, so we render it here in code instead — guaranteeing the SAME
 * mobile-responsive, full-width UI every time. The daily prompt is told to emit
 * a placeholder where this block is injected (see reports/daily.ts).
 */

interface Txn {
  date: string;
  description: string;
  amount: number;
  source: string;
  originalAmount?: number;
  originalCurrency?: string;
}

export interface ExpenseHistoryData {
  currentMonth: string; // "YYYY-MM"
  currentDay: number;
  daysInMonth: number;
  predictedMonthEnd: number;
  monthSoFar: {
    expenses: { living: number };
    categoryBreakdown: Record<string, Txn[]>;
  };
  categoryPace: {
    category: string;
    total: number;
    count: number;
    prevMonthTotal: number;
    dailyBudgetRemaining: number;
    pace: string; // 'high' | 'ok' | 'good'
  }[];
}

const HEB_MONTHS = ['ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני', 'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר'];

const esc = (s: string) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const ils = (n: number) => `₪${Math.abs(Math.round(n)).toLocaleString()}`;
const shortDate = (d: string) => { const p = d.slice(0, 10).split('-'); return p.length === 3 ? `${p[2]}/${p[1]}` : d; };

function paceMeta(pace: string): { light: string; label: string; cls: string } {
  if (pace === 'high') return { light: '🔴', label: 'מעל הקצב', cls: 'eh-high' };
  if (pace === 'good') return { light: '🟢', label: 'מתחת לקצב', cls: 'eh-good' };
  return { light: '🟡', label: 'בקצב', cls: 'eh-ok' };
}

const STYLE = `<style>
  .eh-wrap{direction:rtl;text-align:right;margin:20px 0;}
  .eh-title{font-size:19px;font-weight:800;color:#0f172a;margin:0 0 2px;}
  .eh-sub{font-size:13px;color:#64748b;margin:0 0 14px;}
  .eh-summary{width:100%;border-collapse:collapse;font-size:14px;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;margin:0 0 18px;}
  .eh-summary th{background:#0f172a;color:#fff;text-align:right;padding:10px;font-size:13px;}
  .eh-summary td{padding:10px;border-top:1px solid #eef2f7;}
  .eh-summary tr:nth-child(even) td{background:#f8fafc;}
  .eh-neg{color:#dc2626;font-weight:700;white-space:nowrap;}
  .eh-badge{display:inline-block;padding:2px 9px;border-radius:999px;font-size:12px;font-weight:700;white-space:nowrap;}
  .eh-high{background:#fee2e2;color:#b91c1c;}
  .eh-ok{background:#fef9c3;color:#a16207;}
  .eh-good{background:#dcfce7;color:#15803d;}
  .eh-cat{border:1px solid #e5e7eb;border-radius:10px;margin:0 0 9px;background:#fff;overflow:hidden;}
  .eh-cat>summary{cursor:pointer;list-style:none;padding:12px 13px;font-size:14.5px;font-weight:700;color:#0f172a;background:#f8fafc;}
  .eh-cat>summary::-webkit-details-marker{display:none;}
  .eh-cat[open]>summary{border-bottom:1px solid #e5e7eb;}
  .eh-txns{width:100%;border-collapse:collapse;font-size:13px;table-layout:fixed;}
  .eh-txns th{background:#f1f5f9;color:#475569;text-align:right;padding:8px 11px;font-size:12px;font-weight:700;}
  .eh-txns td{padding:8px 11px;border-top:1px solid #f1f5f9;vertical-align:top;word-break:break-word;}
  .eh-txns tr:nth-child(even) td{background:#fafafa;}
  .eh-date{color:#64748b;white-space:nowrap;}
  .eh-src{font-size:11px;color:#94a3b8;}
  .eh-orig{color:#64748b;font-size:11px;}
  @media only screen and (max-width:600px){
    .eh-title{font-size:17px;}
    .eh-summary th,.eh-summary td{padding:8px 7px;}
    .eh-txns th,.eh-txns td{padding:7px 7px;font-size:12.5px;}
  }
</style>`;

/** Render the month's expense history as a persistent, mobile-responsive block. */
export function renderExpenseHistory(data: ExpenseHistoryData): string {
  const [year, mon] = data.currentMonth.split('-').map(Number);
  const monthLabel = `${HEB_MONTHS[(mon || 1) - 1]} ${year}`;
  const totalSpent = Math.abs(data.monthSoFar.expenses.living);

  // Only categories with spend, biggest first.
  const cats = [...data.categoryPace]
    .filter(c => Math.abs(c.total) > 0)
    .sort((a, b) => Math.abs(b.total) - Math.abs(a.total));

  if (cats.length === 0) return '';

  const summaryRows = cats.map(c => {
    const m = paceMeta(c.pace);
    return `<tr>
      <td>${m.light} ${esc(c.category)}</td>
      <td class="eh-neg">${ils(c.total)}</td>
      <td><span class="eh-badge ${m.cls}">${m.label}</span></td>
    </tr>`;
  }).join('');

  const catBlocks = cats.map(c => {
    const m = paceMeta(c.pace);
    const txns = (data.monthSoFar.categoryBreakdown[c.category] || [])
      .slice()
      .sort((a, b) => a.date.localeCompare(b.date));
    const rows = txns.map(t => {
      const orig = t.originalCurrency
        ? ` <span class="eh-orig">(${Math.abs(t.originalAmount || 0).toLocaleString()} ${esc(t.originalCurrency)})</span>`
        : '';
      return `<tr>
        <td class="eh-date">${shortDate(t.date)}</td>
        <td>${esc(t.description)} <span class="eh-src">· ${esc(t.source)}</span></td>
        <td class="eh-neg">${ils(t.amount)}${orig}</td>
      </tr>`;
    }).join('');
    return `<details class="eh-cat">
      <summary>${m.light} ${esc(c.category)} — <span class="eh-neg">${ils(c.total)}</span> · ${c.count} עסקאות</summary>
      <table class="eh-txns">
        <colgroup><col style="width:20%"><col style="width:55%"><col style="width:25%"></colgroup>
        <thead><tr><th>תאריך</th><th>תיאור</th><th>סכום</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </details>`;
  }).join('');

  return `${STYLE}
<div class="eh-wrap">
  <h2 class="eh-title">היסטוריית הוצאות — ${monthLabel}</h2>
  <div class="eh-sub">יום ${data.currentDay}/${data.daysInMonth} · סה״כ הוצאות מחיה: <b>${ils(totalSpent)}</b> · צפי לסוף החודש: ${ils(data.predictedMonthEnd)}</div>
  <table class="eh-summary">
    <colgroup><col style="width:50%"><col style="width:25%"><col style="width:25%"></colgroup>
    <thead><tr><th>קטגוריה</th><th>הוצאה</th><th>קצב</th></tr></thead>
    <tbody>${summaryRows}</tbody>
  </table>
  ${catBlocks}
</div>`;
}
