/**
 * Deterministic expense-history renderer (shared by daily + monthly reports).
 *
 * The narrative parts of a report are generated by the AI model, so their
 * markup varies run-to-run. The expense breakdown is the part the user reads
 * most, so we render it here in code — guaranteeing the SAME mobile-responsive,
 * full-width UI every time. Reports emit a <!--EXPENSE_HISTORY--> placeholder
 * where this block is injected.
 *
 * - Daily: shows per-category budget pace (🔴/🟡/🟢).
 * - Monthly: shows each category's % of total spend instead of pace.
 * Transactions are listed newest → oldest, and every card shows its total.
 */

interface Txn {
  date: string;
  description: string;
  amount: number;
  source: string;
  originalAmount?: number;
  originalCurrency?: string;
}

interface ExpenseCategory {
  category: string;
  total: number; // negative
  count: number;
  pace?: string;        // 'high' | 'ok' | 'good' (daily only)
  pctOfTotal?: number;  // 0-100 (monthly only)
  transactions: Txn[];
}

// --- Inputs from the two data builders ---

export interface DailyExpenseInput {
  currentMonth: string; // "YYYY-MM"
  currentDay: number;
  daysInMonth: number;
  predictedMonthEnd: number;
  monthSoFar: { expenses: { living: number }; categoryBreakdown: Record<string, Txn[]> };
  categoryPace: { category: string; total: number; count: number; pace: string }[];
}

export interface MonthlyExpenseInput {
  expenses: { living: number };
  categories: { category: string; total: number; count: number }[];
  categoryBreakdown: Record<string, Txn[]>;
}

const HEB_MONTHS = ['ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני', 'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר'];

const esc = (s: string) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const ils = (n: number) => `₪${Math.abs(Math.round(n)).toLocaleString()}`;
const shortDate = (d: string) => { const p = d.slice(0, 10).split('-'); return p.length === 3 ? `${p[2]}/${p[1]}` : d; };
const monthLabel = (ym: string) => { const [y, m] = ym.split('-').map(Number); return `${HEB_MONTHS[(m || 1) - 1]} ${y}`; };

function paceMeta(pace?: string): { light: string; label: string; cls: string } {
  if (pace === 'high') return { light: '🔴', label: 'מעל הקצב', cls: 'eh-high' };
  if (pace === 'good') return { light: '🟢', label: 'מתחת לקצב', cls: 'eh-good' };
  return { light: '🟡', label: 'בקצב', cls: 'eh-ok' };
}

const STYLE = `<style>
  .eh-wrap{direction:rtl;text-align:right;margin:20px 0;}
  .eh-title{font-size:19px;font-weight:800;color:#0f172a;margin:0 0 2px;}
  .eh-sub{font-size:13px;color:#64748b;margin:0 0 14px;}
  .eh-summary{width:100%;border-collapse:collapse;font-size:14px;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;margin:0 0 18px;}
  .eh-summary th{background:#0f172a;color:#fff;text-align:right;padding:10px;font-size:13px;}
  .eh-summary td{padding:10px;border-top:1px solid #eef2f7;}
  .eh-summary tr:nth-child(even) td{background:#f8fafc;}
  .eh-neg{color:#dc2626;font-weight:700;white-space:nowrap;}
  .eh-badge{display:inline-block;padding:2px 9px;border-radius:999px;font-size:12px;font-weight:700;white-space:nowrap;}
  .eh-high{background:#fee2e2;color:#b91c1c;}
  .eh-ok{background:#fef9c3;color:#a16207;}
  .eh-good{background:#dcfce7;color:#15803d;}
  .eh-cat{border:1px solid #e5e7eb;border-radius:10px;margin:0 0 9px;background:#fff;overflow:hidden;}
  .eh-cat>summary{cursor:pointer;list-style:none;padding:12px 13px;font-size:14.5px;font-weight:700;color:#0f172a;background:#f8fafc;}
  .eh-cat>summary::-webkit-details-marker{display:none;}
  .eh-cat[open]>summary{border-bottom:1px solid #e5e7eb;}
  .eh-txns{width:100%;border-collapse:collapse;font-size:13px;table-layout:fixed;}
  .eh-txns th{background:#f1f5f9;color:#475569;text-align:right;padding:8px 11px;font-size:12px;font-weight:700;}
  .eh-txns td{padding:8px 11px;border-top:1px solid #f1f5f9;vertical-align:top;word-break:break-word;}
  .eh-txns tbody tr:nth-child(even) td{background:#fafafa;}
  .eh-txns tfoot td{border-top:2px solid #e5e7eb;font-weight:800;background:#f8fafc;}
  .eh-date{color:#64748b;white-space:nowrap;}
  .eh-src{font-size:11px;color:#94a3b8;}
  .eh-orig{color:#64748b;font-size:11px;}
  @media only screen and (max-width:600px){
    .eh-title{font-size:17px;}
    .eh-summary th,.eh-summary td{padding:8px 7px;}
    .eh-txns th,.eh-txns td{padding:7px 7px;font-size:12.5px;}
  }
</style>`;

/** Core renderer shared by daily and monthly. */
function renderCore(title: string, subtitle: string, cats: ExpenseCategory[], showPace: boolean): string {
  const sorted = cats.filter(c => Math.abs(c.total) > 0).sort((a, b) => Math.abs(b.total) - Math.abs(a.total));
  if (sorted.length === 0) return '';

  const thirdHead = showPace ? 'קצב' : '% מסך';
  const summaryRows = sorted.map(c => {
    const marker = showPace ? `${paceMeta(c.pace).light} ` : '';
    const third = showPace
      ? `<span class="eh-badge ${paceMeta(c.pace).cls}">${paceMeta(c.pace).label}</span>`
      : `${Math.round(c.pctOfTotal || 0)}%`;
    return `<tr><td>${marker}${esc(c.category)}</td><td class="eh-neg">${ils(c.total)}</td><td>${third}</td></tr>`;
  }).join('');

  const catBlocks = sorted.map(c => {
    const marker = showPace ? `${paceMeta(c.pace).light} ` : '';
    // Newest → oldest
    const txns = (c.transactions || []).slice().sort((a, b) => b.date.localeCompare(a.date));
    const rows = txns.map(t => {
      const orig = t.originalCurrency
        ? ` <span class="eh-orig">(${Math.abs(t.originalAmount || 0).toLocaleString()} ${esc(t.originalCurrency)})</span>`
        : '';
      return `<tr><td class="eh-date">${shortDate(t.date)}</td><td>${esc(t.description)} <span class="eh-src">· ${esc(t.source)}</span></td><td class="eh-neg">${ils(t.amount)}${orig}</td></tr>`;
    }).join('');
    return `<details class="eh-cat">
      <summary>${marker}${esc(c.category)} — <span class="eh-neg">${ils(c.total)}</span> · ${c.count} עסקאות</summary>
      <table class="eh-txns">
        <colgroup><col style="width:20%"><col style="width:55%"><col style="width:25%"></colgroup>
        <thead><tr><th>תאריך</th><th>תיאור</th><th>סכום</th></tr></thead>
        <tbody>${rows}</tbody>
        <tfoot><tr><td colspan="2">סה״כ</td><td class="eh-neg">${ils(c.total)}</td></tr></tfoot>
      </table>
    </details>`;
  }).join('');

  return `${STYLE}
<div class="eh-wrap">
  <h2 class="eh-title">${title}</h2>
  <div class="eh-sub">${subtitle}</div>
  <table class="eh-summary">
    <colgroup><col style="width:50%"><col style="width:25%"><col style="width:25%"></colgroup>
    <thead><tr><th>קטגוריה</th><th>הוצאה</th><th>${thirdHead}</th></tr></thead>
    <tbody>${summaryRows}</tbody>
  </table>
  ${catBlocks}
</div>`;
}

/** Daily: month-to-date expense history with budget pace. */
export function renderExpenseHistory(data: DailyExpenseInput): string {
  const cats: ExpenseCategory[] = data.categoryPace.map(c => ({
    category: c.category, total: c.total, count: c.count, pace: c.pace,
    transactions: data.monthSoFar.categoryBreakdown[c.category] || [],
  }));
  const total = Math.abs(data.monthSoFar.expenses.living);
  const subtitle = `יום ${data.currentDay}/${data.daysInMonth} · סה״כ הוצאות מחיה: <b>${ils(total)}</b> · צפי לסוף החודש: ${ils(data.predictedMonthEnd)}`;
  return renderCore(`היסטוריית הוצאות — ${monthLabel(data.currentMonth)}`, subtitle, cats, true);
}

/** Monthly: full-month expense history with each category's % of total. */
export function renderMonthlyExpenseHistory(data: MonthlyExpenseInput, month: string): string {
  const total = Math.abs(data.expenses.living);
  const cats: ExpenseCategory[] = data.categories.map(c => ({
    category: c.category, total: c.total, count: c.count,
    pctOfTotal: total ? (Math.abs(c.total) / total) * 100 : 0,
    transactions: data.categoryBreakdown[c.category] || [],
  }));
  const subtitle = `סה״כ הוצאות מחיה: <b>${ils(total)}</b>`;
  return renderCore(`היסטוריית הוצאות — ${monthLabel(month)}`, subtitle, cats, false);
}
